# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
#on:
  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
    
on:
  push:
    paths: 
    - '.github/workflows/deployProd.yml'
  pull_request:    
    paths: 
    - '.github/workflows/deployProd.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: pwd
      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./ARM-Templates/container-webapp-template-prod.json

      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}